apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsb.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tsb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tsb.postgresSelector" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
